---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: medi-comply
  labels:
    app: medi-comply
    component: postgres
spec:
  type: ClusterIP
  selector:
    app: medi-comply
    component: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
