"""Compliance package for MEDI-COMPLY.

Provides HIPAA safeguards including PHI detection, reversible de-identification,
LLM safety checks, access logging, compliance auditing, minimum-necessary role
enforcement, and retention utilities.
"""

from medi_comply.compliance.hipaa_guard import (
    PHIIdentifierType,
    PHIDetector,
    Deidentifier,
    LLMPHISafetyChecker,
    HIPAAAccessLogger,
    HIPAAComplianceChecker,
    MinimumNecessaryRule,
    DataRetentionManager,
    PHIDetection,
    DeidentificationResult,
    ReidentificationResult,
    AccessLogEntry,
    HIPAAComplianceStatus,
)
from medi_comply.compliance.fraud_detector import (
    FraudType,
    FraudSeverity,
    FraudAlert,
    FraudDetectionResult,
    FraudDetector,
    UpcodingDetector,
    UnbundlingDetector,
    DuplicateBillingDetector,
    FrequencyAbuseDetector,
    ModifierAbuseDetector,
    BillingPatternAnalyzer,
    UPCODING_PAIRS,
    LAB_PANELS,
)
from medi_comply.compliance.parity_checker import (
    ServiceClassification,
    BenefitCategory,
    LimitationType,
    ParityViolationType,
    BenefitComparison,
    ParityViolation,
    ParityCheckResult,
    BenefitDetail,
    PlanBenefits,
    ServiceClassifier,
    ParityComparator,
    ParityChecker,
    COMPARABLE_SERVICES,
    get_sample_plan_benefits,
)
from medi_comply.compliance.regulatory_calendar import (
    RegulatoryBody,
    RegulationType,
    RegulationStatus,
    UrgencyLevel,
    RegulatoryEvent,
    DOSValidationResult,
    ComplianceDeadline,
    CodeSetVersionTracker,
    StalenessDetector,
    RegulatoryCalendar,
)

__all__ = [
    "PHIIdentifierType",
    "PHIDetector",
    "Deidentifier",
    "LLMPHISafetyChecker",
    "HIPAAAccessLogger",
    "HIPAAComplianceChecker",
    "MinimumNecessaryRule",
    "DataRetentionManager",
    "PHIDetection",
    "DeidentificationResult",
    "ReidentificationResult",
    "AccessLogEntry",
    "HIPAAComplianceStatus",
    "FraudType",
    "FraudSeverity",
    "FraudAlert",
    "FraudDetectionResult",
    "FraudDetector",
    "UpcodingDetector",
    "UnbundlingDetector",
    "DuplicateBillingDetector",
    "FrequencyAbuseDetector",
    "ModifierAbuseDetector",
    "BillingPatternAnalyzer",
    "UPCODING_PAIRS",
    "LAB_PANELS",
    "ServiceClassification",
    "BenefitCategory",
    "LimitationType",
    "ParityViolationType",
    "BenefitComparison",
    "ParityViolation",
    "ParityCheckResult",
    "BenefitDetail",
    "PlanBenefits",
    "ServiceClassifier",
    "ParityComparator",
    "ParityChecker",
    "COMPARABLE_SERVICES",
    "get_sample_plan_benefits",
    "RegulatoryBody",
    "RegulationType",
    "RegulationStatus",
    "UrgencyLevel",
    "RegulatoryEvent",
    "DOSValidationResult",
    "ComplianceDeadline",
    "CodeSetVersionTracker",
    "StalenessDetector",
    "RegulatoryCalendar",
]
