"""Seed data: NCCI edit pairs, MUE entries, LCD entries, and Coding Guidelines."""
from medi_comply.knowledge.ncci_engine import NCCIEditPair, MUEEntry
from medi_comply.knowledge.medical_necessity import CoverageDetermination
from medi_comply.knowledge.coding_guidelines import CodingGuideline, CodingExample

_P = NCCIEditPair
_M = MUEEntry
_L = CoverageDetermination
_G = CodingGuideline
_X = CodingExample


def get_ncci_pairs() -> list[NCCIEditPair]:
    """Return 30+ real NCCI PTP edit pairs."""
    return [
        _P(column1_code="93453", column2_code="93451", modifier_indicator="1", ptp_edit_rationale="Combined cath bundles right cath; modifier allowed for separate session"),
        _P(column1_code="93453", column2_code="93452", modifier_indicator="1", ptp_edit_rationale="Combined cath bundles left cath; modifier allowed for separate session"),
        _P(column1_code="80053", column2_code="80048", modifier_indicator="0", ptp_edit_rationale="CMP includes all BMP components; no modifier override"),
        _P(column1_code="99215", column2_code="99213", modifier_indicator="0", ptp_edit_rationale="Higher-level E/M bundles lower-level E/M same day"),
        _P(column1_code="99215", column2_code="99214", modifier_indicator="0", ptp_edit_rationale="Higher-level E/M bundles lower-level E/M same day"),
        _P(column1_code="99215", column2_code="99212", modifier_indicator="0", ptp_edit_rationale="Higher-level E/M bundles lower-level E/M same day"),
        _P(column1_code="99214", column2_code="99213", modifier_indicator="0", ptp_edit_rationale="Higher-level E/M bundles lower-level E/M same day"),
        _P(column1_code="93306", column2_code="93308", modifier_indicator="0", ptp_edit_rationale="Complete echo bundles limited/follow-up echo"),
        _P(column1_code="93306", column2_code="93307", modifier_indicator="0", ptp_edit_rationale="Complete echo bundles 2D echo"),
        _P(column1_code="71260", column2_code="71250", modifier_indicator="0", ptp_edit_rationale="CT with contrast bundles CT without contrast same session"),
        _P(column1_code="92920", column2_code="92921", modifier_indicator="9", ptp_edit_rationale="PCI add-on code; 92921 is add-on to 92920"),
        _P(column1_code="99291", column2_code="99292", modifier_indicator="9", ptp_edit_rationale="Critical care add-on; 99292 is add-on to 99291"),
        _P(column1_code="85025", column2_code="85027", modifier_indicator="0", ptp_edit_rationale="CBC with diff bundles automated CBC"),
        _P(column1_code="93000", column2_code="93010", modifier_indicator="0", ptp_edit_rationale="Complete ECG bundles interpretation only"),
        _P(column1_code="99223", column2_code="99221", modifier_indicator="0", ptp_edit_rationale="Higher initial hospital care bundles lower"),
        _P(column1_code="99223", column2_code="99222", modifier_indicator="0", ptp_edit_rationale="Higher initial hospital care bundles lower"),
        _P(column1_code="99285", column2_code="99283", modifier_indicator="0", ptp_edit_rationale="Higher ER visit bundles lower"),
        _P(column1_code="99285", column2_code="99284", modifier_indicator="0", ptp_edit_rationale="Higher ER visit bundles lower"),
        _P(column1_code="99284", column2_code="99283", modifier_indicator="0", ptp_edit_rationale="Higher ER visit bundles lower"),
        _P(column1_code="93458", column2_code="93451", modifier_indicator="1", ptp_edit_rationale="Coronary angiography bundles right heart cath"),
        _P(column1_code="93458", column2_code="93452", modifier_indicator="1", ptp_edit_rationale="Coronary angiography bundles left heart cath"),
        _P(column1_code="80053", column2_code="82565", modifier_indicator="0", ptp_edit_rationale="CMP includes creatinine"),
        _P(column1_code="80053", column2_code="82947", modifier_indicator="0", ptp_edit_rationale="CMP includes glucose"),
        _P(column1_code="80053", column2_code="82310", modifier_indicator="0", ptp_edit_rationale="CMP includes calcium"),
        _P(column1_code="80048", column2_code="82565", modifier_indicator="0", ptp_edit_rationale="BMP includes creatinine"),
        _P(column1_code="80048", column2_code="82947", modifier_indicator="0", ptp_edit_rationale="BMP includes glucose"),
        _P(column1_code="94060", column2_code="94010", modifier_indicator="0", ptp_edit_rationale="Bronchodilator response includes pre-bronchodilator spirometry"),
        _P(column1_code="99233", column2_code="99231", modifier_indicator="0", ptp_edit_rationale="Higher subsequent hospital care bundles lower"),
        _P(column1_code="99233", column2_code="99232", modifier_indicator="0", ptp_edit_rationale="Higher subsequent hospital care bundles lower"),
        _P(column1_code="99232", column2_code="99231", modifier_indicator="0", ptp_edit_rationale="Higher subsequent hospital care bundles lower"),
        _P(column1_code="93312", column2_code="93306", modifier_indicator="1", ptp_edit_rationale="TEE bundles TTE same session; modifier for separate session"),
    ]


def get_mue_entries() -> list[MUEEntry]:
    """Return 15+ MUE entries."""
    return [
        _M(cpt_code="99213", mue_value=1, mue_rationale="Clinical: nature of service", mue_adjudication="line"),
        _M(cpt_code="99214", mue_value=1, mue_rationale="Clinical: nature of service", mue_adjudication="line"),
        _M(cpt_code="99215", mue_value=1, mue_rationale="Clinical: nature of service", mue_adjudication="line"),
        _M(cpt_code="99291", mue_value=1, mue_rationale="Clinical: one initial critical care per day", mue_adjudication="line"),
        _M(cpt_code="99292", mue_value=4, mue_rationale="Clinical: additional 30-min increments", mue_adjudication="line"),
        _M(cpt_code="93000", mue_value=3, mue_rationale="Clinical: up to 3 ECGs per day reasonable", mue_adjudication="claim"),
        _M(cpt_code="84484", mue_value=3, mue_rationale="Clinical: serial troponin draws reasonable", mue_adjudication="claim"),
        _M(cpt_code="71046", mue_value=2, mue_rationale="Clinical: up to 2 chest x-rays per day", mue_adjudication="claim"),
        _M(cpt_code="80048", mue_value=1, mue_rationale="Clinical: panel run once per encounter", mue_adjudication="line"),
        _M(cpt_code="80053", mue_value=1, mue_rationale="Clinical: panel run once per encounter", mue_adjudication="line"),
        _M(cpt_code="94640", mue_value=4, mue_rationale="Clinical: nebulizer treatments can repeat", mue_adjudication="claim"),
        _M(cpt_code="85025", mue_value=2, mue_rationale="Clinical: CBC reasonable twice per day", mue_adjudication="claim"),
        _M(cpt_code="93306", mue_value=1, mue_rationale="Clinical: one complete echo per encounter", mue_adjudication="line"),
        _M(cpt_code="70553", mue_value=1, mue_rationale="Clinical: one brain MRI per encounter", mue_adjudication="line"),
        _M(cpt_code="83036", mue_value=1, mue_rationale="Clinical: HbA1c once per encounter", mue_adjudication="line"),
    ]


def get_lcd_entries() -> list[CoverageDetermination]:
    """Return 10+ LCD entries for medical necessity."""
    return [
        _L(lcd_id="LCD-33640", lcd_title="Transthoracic Echocardiography (TTE)", procedure_codes=["93306","93307","93308"], covered_icd10_codes=["I50.1","I50.20","I50.21","I50.22","I50.23","I25.10","I21.0","I21.4","I48.0","I48.1","I48.91","R00.0","R00.1","R07.9","I11.0","I11.9","I63.30"], documentation_requirements=["Clinical indication for the study","Relevant signs and symptoms","Previous cardiac history if applicable"], frequency_limits="Once per 12 months unless clinical change"),
        _L(lcd_id="LCD-33641", lcd_title="Cardiac Catheterization", procedure_codes=["93451","93452","93453","93458"], covered_icd10_codes=["I21.0","I21.01","I21.02","I21.09","I21.11","I21.19","I21.4","I25.10","I25.110","I25.119","I50.20","I50.21","I50.22","I50.23","R07.1","R07.2","R07.9","I48.0"], documentation_requirements=["Clinical indication","Failed medical management or acute presentation","Risk-benefit analysis documented"], frequency_limits="As clinically indicated"),
        _L(lcd_id="LCD-33642", lcd_title="CT Chest", procedure_codes=["71250","71260"], covered_icd10_codes=["J18.0","J18.1","J18.9","J44.0","J44.1","J80","J96.00","J96.01","J96.02","R07.1","R07.9","R06.00","R06.02","U07.1","I63.30"], documentation_requirements=["Clinical indication","Symptoms or physical findings warranting imaging"], frequency_limits="As clinically indicated"),
        _L(lcd_id="LCD-33643", lcd_title="MRI Brain", procedure_codes=["70553"], covered_icd10_codes=["I63.30","I63.311","I63.312","R51.0","R51.9","R40.20","R55","S06.0X0A","S06.0X1A","R42"], documentation_requirements=["Clinical indication","Neurological symptoms documented","Prior imaging results if applicable"], frequency_limits="As clinically indicated"),
        _L(lcd_id="LCD-33644", lcd_title="Electrocardiogram", procedure_codes=["93000","93010"], covered_icd10_codes=["I21.0","I21.4","I25.10","I48.0","I48.1","I48.2","I48.91","I50.1","I50.20","I50.21","R07.1","R07.2","R07.9","R00.0","R00.1","R55","R06.00"], documentation_requirements=["Clinical indication"], frequency_limits="As clinically indicated"),
        _L(lcd_id="LCD-33645", lcd_title="Troponin Testing", procedure_codes=["84484"], covered_icd10_codes=["I21.0","I21.01","I21.02","I21.4","I25.10","R07.1","R07.2","R07.9","R06.00","R55","I50.21","I50.23"], documentation_requirements=["Suspected ACS or myocardial injury","Serial testing timing documented"], frequency_limits="Up to 3 per encounter for serial testing"),
        _L(lcd_id="LCD-33646", lcd_title="Hemoglobin A1c", procedure_codes=["83036"], covered_icd10_codes=["E11.00","E11.01","E11.10","E11.22","E11.65","E11.9","E10.10","E10.9","E13.9","R73.01","R73.02"], documentation_requirements=["Diabetes diagnosis or screening indication"], frequency_limits="Once per 3 months for diagnosed diabetes"),
        _L(lcd_id="LCD-33647", lcd_title="Spirometry", procedure_codes=["94010","94060"], covered_icd10_codes=["J44.0","J44.1","J44.9","J45.20","J45.21","J45.22","J45.30","J45.31","R06.00","R06.02","R06.09"], documentation_requirements=["Respiratory symptoms","Prior diagnosis of obstructive lung disease"], frequency_limits="As clinically indicated"),
        _L(lcd_id="LCD-33648", lcd_title="Complete Blood Count", procedure_codes=["85025"], covered_icd10_codes=["I21.0","I21.4","J18.9","R50.9","N39.0","J96.00","J96.01","U07.1","I50.21","R09.02"], documentation_requirements=["Clinical indication for hematologic evaluation"], frequency_limits="As clinically indicated"),
        _L(lcd_id="LCD-33649", lcd_title="Metabolic Panel", procedure_codes=["80048","80053"], covered_icd10_codes=["N18.1","N18.2","N18.30","N18.4","N18.5","N18.6","N18.9","N17.0","N17.9","E11.22","E11.9","I50.20","I50.21","I50.22","I50.23","R50.9"], documentation_requirements=["Clinical indication"], frequency_limits="As clinically indicated"),
    ]


def get_coding_guidelines() -> list[CodingGuideline]:
    """Return 15+ ICD-10-CM Official Coding Guidelines."""
    return [
        _G(guideline_id="OCG-I-A-13", section="I", subsection="A", chapter="13", title="Etiology/Manifestation convention", rule_text="Certain conditions have both an underlying etiology and multiple body system manifestations due to the underlying etiology. The ICD-10-CM has coding conventions that require the underlying condition be sequenced first, followed by the manifestation.", applies_to_codes=["E08-E13","G00-G99","H00-H59"], scenario_keywords=["etiology","manifestation","underlying condition","sequencing"], examples=[_X(scenario="Diabetic retinopathy", correct_coding=["E11.319"], explanation="Combination code includes both etiology and manifestation.")]),
        _G(guideline_id="OCG-I-A-15", section="I", subsection="A", chapter="15", title="Code First and Use Additional Code notes", rule_text="Etiology/manifestation paired codes are designated by 'Code first' and 'Use additional code' notes. The 'Code first' note indicates the underlying condition should be sequenced first. The 'Use additional code' note at the etiology code indicates a manifestation code should follow.", applies_to_codes=["E08-E13","N18"], scenario_keywords=["code first","use additional","sequencing","paired codes"], examples=[_X(scenario="T2DM with CKD stage 3", correct_coding=["E11.22","N18.30"], explanation="E11.22 instructs 'Use additional code N18.- to identify stage of CKD'. Code E11.22 first, then N18.30.")]),
        _G(guideline_id="OCG-I-A-17", section="I", subsection="A", chapter="17", title="Excludes1 vs Excludes2 notes", rule_text="An Excludes1 note means 'NOT CODED HERE'. The two conditions cannot occur together. An Excludes2 note means 'Not included here' but the excluded condition may coexist and both codes may be used together if documented.", applies_to_codes=[], scenario_keywords=["excludes1","excludes2","mutually exclusive","coexist"], examples=[_X(scenario="Type 1 and Type 2 DM codes", correct_coding=["E11.9"], explanation="E10 and E11 are Excludes1 — cannot be coded together. A patient has one type of diabetes.")]),
        _G(guideline_id="OCG-I-B-4", section="I", subsection="B", chapter="4", title="Laterality", rule_text="Some ICD-10-CM codes indicate laterality, specifying whether the condition occurs on the left, right or is bilateral. If no bilateral code is provided and the condition is bilateral, assign separate codes for both the left and right side.", applies_to_codes=["I63","S72","S52","S42","S82","S62"], scenario_keywords=["laterality","left","right","bilateral"], examples=[_X(scenario="Bilateral cerebral infarction", correct_coding=["I63.311","I63.312"], explanation="When bilateral and no bilateral code exists, code each side separately.")]),
        _G(guideline_id="OCG-I-B-7", section="I", subsection="B", chapter="7", title="7th Character for episode of care", rule_text="The 7th character indicates the episode of care: A = initial encounter, D = subsequent encounter, S = sequela. The 7th character is required for certain injury, poisoning, and external cause codes.", applies_to_codes=["S00-T88","V00-Y99"], scenario_keywords=["7th character","initial encounter","subsequent","sequela","episode of care"], examples=[_X(scenario="Hip fracture initial treatment", correct_coding=["S72.001A"], explanation="A = initial encounter when patient is receiving active treatment for the condition.")]),
        _G(guideline_id="OCG-I-C-4-a", section="I", subsection="C", chapter="4.a", title="Diabetes mellitus - General coding guidelines", rule_text="The diabetes mellitus codes are combination codes that include the type of diabetes mellitus, the body system affected, and the complications affecting that body system. As many codes within a particular category as are necessary to describe all of the complications of the disease may be used. They should be sequenced based on the reason for a particular encounter.", applies_to_codes=["E08-E13"], scenario_keywords=["diabetes","DM","diabetic complication","type 2","type 1","combination code"], examples=[_X(scenario="Patient has T2DM with diabetic nephropathy and retinopathy", correct_coding=["E11.22","N18.30","E11.319"], explanation="Use combination codes for each complication. Use additional code for CKD stage per instruction at E11.22.")]),
        _G(guideline_id="OCG-I-C-4-a-2", section="I", subsection="C", chapter="4.a.2", title="Diabetes mellitus with kidney complications", rule_text="When assigning codes for diabetes with kidney complications, assign codes from subcategory E11.2 (or the appropriate diabetes type). Follow the 'Use additional code' note to assign the appropriate N18 code for the stage of CKD.", applies_to_codes=["E08-E13","N18"], scenario_keywords=["diabetes","kidney","nephropathy","CKD","renal"], examples=[_X(scenario="T2DM with CKD stage 4", correct_coding=["E11.22","N18.4"], explanation="E11.22 for DM with CKD, plus N18.4 for stage 4.")]),
        _G(guideline_id="OCG-I-C-4-a-3", section="I", subsection="C", chapter="4.a.3", title="Diabetes mellitus with ophthalmic complications", rule_text="When assigning codes for diabetes with ophthalmic complications, codes from subcategories E11.31-E11.36 identify the type of retinopathy. Assign as many codes as necessary to identify all associated conditions.", applies_to_codes=["E08-E13"], scenario_keywords=["diabetes","retinopathy","ophthalmic","eye","macular edema"], examples=[_X(scenario="T2DM with proliferative diabetic retinopathy with macular edema", correct_coding=["E11.311"], explanation="Combination code identifies both retinopathy type and macular edema.")]),
        _G(guideline_id="OCG-I-C-4-a-6", section="I", subsection="C", chapter="4.a.6", title="Diabetes mellitus with associated conditions", rule_text="When the documentation links a condition to diabetes, assign the appropriate combination code from E11 (or appropriate type). When the documentation does not indicate a causal relationship, code the diabetes and the associated condition separately.", applies_to_codes=["E08-E13"], scenario_keywords=["diabetes","associated","complication","causal","linked"], examples=[]),
        _G(guideline_id="OCG-I-C-9-a", section="I", subsection="C", chapter="9.a", title="Hypertension coding", rule_text="Assign codes from categories I10-I16 for hypertension. If the provider has documented a causal relationship between hypertension and heart disease, assign a code from category I11, Hypertensive heart disease. The same heart conditions (I50.-, I51.4-I51.9) are coded differently based on the causal relationship.", applies_to_codes=["I10-I16","I50"], scenario_keywords=["hypertension","HTN","blood pressure","hypertensive heart disease"], examples=[_X(scenario="Hypertensive heart disease with heart failure", correct_coding=["I11.0","I50.9"], explanation="Use I11.0 with additional code for type of heart failure. Do NOT code I10 separately.")]),
        _G(guideline_id="OCG-I-C-9-a-1", section="I", subsection="C", chapter="9.a.1", title="Hypertension with heart disease", rule_text="Hypertension with heart conditions classified to I50.- or I51.4-I51.7, I51.89, I51.9, are assigned to a code from category I11 when a causal relationship is stated or implied. Use additional code(s) from category I50 to identify the type(s) of heart failure.", applies_to_codes=["I11","I50"], scenario_keywords=["hypertension","heart failure","hypertensive heart disease","I11"], examples=[]),
        _G(guideline_id="OCG-I-C-9-e", section="I", subsection="C", chapter="9.e", title="Myocardial infarction coding (STEMI/NSTEMI)", rule_text="Category I21 distinguishes between STEMI and NSTEMI. If an NSTEMI converts to a STEMI, assign only the STEMI code. If a type 1 AMI is documented as nontransmural or subendocardial but the site is provided, assign the appropriate code for STEMI.", applies_to_codes=["I21"], scenario_keywords=["STEMI","NSTEMI","myocardial infarction","MI","heart attack","acute MI"], examples=[_X(scenario="Acute STEMI of left anterior descending artery", correct_coding=["I21.02"], explanation="I21.02 for STEMI involving LAD coronary artery.")]),
        _G(guideline_id="OCG-I-C-10-b", section="I", subsection="C", chapter="10.b", title="COPD coding", rule_text="Codes in category J44 distinguish between COPD with acute exacerbation (J44.1) and COPD with acute lower respiratory infection (J44.0). Use additional code to identify the infection. These two conditions are Excludes1 — they cannot be coded together.", applies_to_codes=["J44"], scenario_keywords=["COPD","chronic obstructive","exacerbation","pulmonary disease","bronchitis"], examples=[_X(scenario="COPD with acute pneumonia", correct_coding=["J44.0","J18.9"], explanation="J44.0 for COPD with infection, plus additional code to identify the pneumonia.")]),
        _G(guideline_id="OCG-I-C-14-a", section="I", subsection="C", chapter="14.a", title="Chronic kidney disease coding", rule_text="The ICD-10-CM classifies CKD based on severity identified by stages 1-5. Code first the underlying cause (such as diabetes E08-E13 with .22). Stage of CKD is identified by codes N18.1-N18.6, N18.9 for unspecified.", applies_to_codes=["N18","E08-E13"], scenario_keywords=["CKD","chronic kidney disease","renal","stage","end stage"], examples=[_X(scenario="CKD stage 3a due to T2DM", correct_coding=["E11.22","N18.31"], explanation="Code diabetes first per Code-first note at N18, then stage.")]),
        _G(guideline_id="OCG-II-A", section="II", subsection="A", title="Principal diagnosis selection - Inpatient", rule_text="The principal diagnosis is defined as the condition established after study to be chiefly responsible for occasioning the admission. The principal diagnosis is sequenced first.", applies_to_codes=[], scenario_keywords=["principal diagnosis","inpatient","admission","sequencing","PDX"], examples=[_X(scenario="Admitted for CHF exacerbation with COPD", correct_coding=["I50.21","J44.9"], explanation="The condition chiefly responsible for admission is sequenced first.")]),
        _G(guideline_id="OCG-IV-D", section="IV", subsection="D", title="Outpatient - Uncertain diagnoses", rule_text="Do not code diagnoses documented as 'probable', 'suspected', 'questionable', 'rule out', or 'working diagnosis' for outpatient encounters. Instead, code the condition(s) to the highest degree of certainty — the signs, symptoms, or abnormal findings.", applies_to_codes=[], scenario_keywords=["uncertain","probable","suspected","rule out","outpatient","symptoms"], examples=[_X(scenario="Outpatient visit for 'suspected pneumonia'", correct_coding=["R06.00","R50.9"], explanation="Code symptoms (dyspnea, fever) not the suspected diagnosis.")]),
        _G(guideline_id="OCG-IV-J", section="IV", subsection="J", title="Outpatient - Code to highest specificity", rule_text="Code all documented conditions that coexist at the time of the encounter and require or affect patient care, treatment, or management. Code to the highest level of specificity.", applies_to_codes=[], scenario_keywords=["specificity","highest","outpatient","documented conditions","coexist"], examples=[_X(scenario="T2DM with neuropathy", correct_coding=["E11.42"], explanation="Use the most specific combination code (E11.42 for polyneuropathy) rather than unspecified E11.9.")]),
    ]
