---
apiVersion: v1
kind: Service
metadata:
  name: nlp-service
  namespace: medi-comply
  labels:
    app: medi-comply
    component: nlp
spec:
  type: ClusterIP
  selector:
    app: medi-comply
    component: nlp
  ports:
    - name: http
      port: 8001
      targetPort: 8001
